services:
  frontend:
    image: kcarestore/kcs-client:latest
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    image: kcarestore/kcs-server:latest
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - app-network
    environment:
      REDIS_HOST: redis-stack
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    environment:
      - REDIS_ARGS=--maxmemory 512mb --maxmemory-policy allkeys-lru


  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email lhoangcuong1996@gmail.com -d khanhstore.com -d www.khanhstore.com -d api.khanhstore.com -d www.api.khanhstore.com --agree-tos --non-interactive
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
  certs:
    driver: local
